# Generated by Django 4.1.7 on 2023-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
