# Generated by Django 4.1.7 on 2023-03-05 17:03

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Oyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_text', models.TextField()),
                ('uzbek_text', models.TextField()),
                ('audio_file', models.FileField(null=True, upload_to='oyat_audio')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quroni_karim.sura')),
            ],
        ),
    ]
