# Generated by Django 4.1.7 on 2023-03-03 17:16

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamozVaqtlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mintaqa', models.CharField(max_length=300)),
                ('bomdod', models.TimeField(null=True)),
                ('quyosh', models.TimeField(null=True)),
                ('peshin', models.TimeField(null=True)),
                ('asr', models.TimeField(null=True)),
                ('shom', models.TimeField(null=True)),
                ('xufton', models.TimeField(null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
